### ISSUE TITLE
Define own buckets

### ISSUE THREAD

**Issue by BAGrimReefer** [PrometheusClientNet/Prometheus.Client.HttpRequestDurations#2]
Hi,

thanks for this tool! Would it be please possible to implement own bucket sizes to Histogram? Histogram supports this operation so it shouldn't be complicated (`Metrics.CreateHistogram("my_histogram", "help text", buckets: new[] { 0, 0.2, 0.4, 0.6, 0.8, 0.9 });`).

Thanks.

Martin

**Comment by phnx47** [comment]
Hi!

Yes, I will add it in Options.

**Comment by phnx47** [comment]
v0.4.0
