### ISSUE TITLE
Path Normalization

### ISSUE THREAD

**Issue by phnx47** [PrometheusClientNet/Prometheus.Client.HttpRequestDurations#3]
Add 'Path Normalization' with regex.

Dirty version: https://github.com/PrometheusClientNet/Prometheus.Client.HttpRequestDurations/pull/1/files

**Comment by zihotki** [comment]
Another option could be to use Route (api/cities/{id}) instead of a Path (api/cities/2342) and avoid using RegExes if possible. This way it'll be also easier to detect wildcard routes "/api/search/{*searchString}". What do you think?

**Comment by phnx47** [comment]
I will write prototype for test. And then I'll think about how best to work with it.

**Comment by dmeenhuis** [comment]
Any progress with this? I'm trying to get metrics for request durations that also include paths, but it would be a lot more useful if there is a way to normalize ID values.

**Comment by phnx47** [comment]
@dmeenhuis I will come back to this issue soon.

Thank you!

**Comment by zihotki** [comment]
> Thanks! I managed to fork this repo and incorporate the changes in the linked PR and for now...

Is it me or you didn't push or create a PR? I can't find it in this repo

**Comment by phnx47** [comment]
I finished work with this:https://github.com/PrometheusClientNet/Prometheus.Client/issues/18

Now, I can come back to this issue

**Comment by phnx47** [comment]
Released. 1.1.0

**Comment by phnx47** [comment]
Regex [examples](https://github.com/PrometheusClientNet/Prometheus.Client.HttpRequestDurations/blob/master/tests/Prometheus.Client.HttpRequestDurations.Tests/NormalizePathTests.cs)

**Comment by phnx47** [comment]
If something does not work, then reopen.
